// Builds the template grammar from data/catalog.json, so the functions the
// grammar colours are exactly the ones completion offers. Run by `npm run build`.
import { readFileSync, writeFileSync } from "node:fs";

const catalog = JSON.parse(readFileSync(new URL("../data/catalog.json", import.meta.url)));
const words = (list) => `\\b(?:${list.map((w) => w.replace(/[$^*+?.()|[\]{}\\]/g, "\\$&")).join("|")})\\b`;

const core = catalog.functions.filter((f) => f.source === "collage").map((f) => f.name);
const plugins = catalog.functions.filter((f) => f.source !== "collage").map((f) => f.name);

// The expression inside {{ … }}: what Go's text/template accepts, with collage's
// functions and the plugins' told apart from Go's own builtins.
const expression = [
  { include: "#comment" },
  {
    name: "keyword.control.collage-template",
    match: words(catalog.builtins.keywords),
  },
  {
    name: "support.function.collage.core",
    match: `(?<![.$\\w])${words(core)}`,
  },
  {
    name: "support.function.collage.plugin",
    match: `(?<![.$\\w])${words(plugins)}`,
  },
  {
    name: "support.function.builtin.collage-template",
    match: `(?<![.$\\w])${words(catalog.builtins.functions)}`,
  },
  { name: "constant.language.collage-template", match: "\\b(?:true|false|nil)\\b" },
  { name: "string.quoted.double.collage-template", begin: "\"", end: "\"", patterns: [{ name: "constant.character.escape.collage-template", match: "\\\\." }] },
  { name: "string.quoted.raw.collage-template", begin: "`", end: "`" },
  { name: "string.quoted.single.collage-template", match: "'(?:\\\\.|[^'\\\\])'" },
  { name: "constant.numeric.collage-template", match: "-?\\b\\d+(?:\\.\\d+)?\\b" },
  { name: "variable.other.collage-template", match: "\\$\\w*" },
  { name: "variable.other.member.collage-template", match: "\\.[A-Za-z_]\\w*" },
  { name: "variable.language.dot.collage-template", match: "(?<![\\w)])\\.(?![\\w])" },
  { name: "keyword.operator.assignment.collage-template", match: ":=|=" },
  { name: "keyword.operator.pipe.collage-template", match: "\\|" },
  { name: "punctuation.section.parens.collage-template", match: "[()]" },
];

const grammar = {
  $schema: "https://raw.githubusercontent.com/martinring/tmlanguage/master/tmlanguage.json",
  name: "Collage Template",
  scopeName: "collage.template.injection",
  comment: "Generated by scripts/build-grammar.mjs from data/catalog.json — edit those, not this.",
  // Injected into HTML rather than defining a language of its own, so a template
  // stays HTML: Emmet, tag completion and formatting keep working. L: gives the
  // template's tokens priority over HTML's, inside attribute values too.
  injectionSelector: "L:text.html -comment.block.html",
  patterns: [{ include: "#action" }],
  repository: {
    action: {
      name: "meta.embedded.block.collage-template",
      begin: "\\{\\{-?",
      beginCaptures: { 0: { name: "punctuation.section.embedded.begin.collage-template" } },
      end: "-?\\}\\}",
      endCaptures: { 0: { name: "punctuation.section.embedded.end.collage-template" } },
      patterns: expression,
    },
    comment: {
      name: "comment.block.collage-template",
      begin: "/\\*",
      end: "\\*/",
    },
  },
};

writeFileSync(new URL("../syntaxes/collage-template.tmLanguage.json", import.meta.url), JSON.stringify(grammar, null, 2) + "\n");
console.log(`grammar: ${core.length} collage functions, ${plugins.length} plugin functions`);
